add error checking

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,16 @@
 #!/bin/bash
+
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable is not set."
+    exit 1
+fi
+
+
+if [ ! -f "$PYFILE" ]; then
+    echo  "Error: Python file '$PYFILE' not found."
+    exit 1
+
+fi
+
+#Run the Python script
 python3 $PYFILE
